name: 'ECA Config'
type: module
description: 'Config events.'
core_version_requirement: ^11.2
package: ECA
dependencies:
  - eca:eca

# Information added by Drupal.org packaging script on 2025-08-16
version: '3.0.2'
project: 'eca'
datestamp: 1755341168
